import { registerAs } from '@nestjs/config';

/**
 * Purpose
 * -------
 * Defines Redis configuration values loaded from environment variables.
 * Exposes them under the key 'redis' for ConfigService access.
 */

/**
 * Redis Configuration
 * -------------------
 * Registered under key 'redis' -> configService.get('redis.*')
 */
export default registerAs('redis', () => ({
  /**
   * Host name or IP address for the Redis server.
   * Default: 'localhost'
   */
  host: process.env.REDIS_HOST || 'localhost',

  /**
   * TCP port for the Redis server.
   * Default: 6379
   */
  port: process.env.REDIS_PORT ? parseInt(process.env.REDIS_PORT, 10) : 6379,

  /**
   * Password used for Redis AUTH.
   * Default: empty string
   */
  password: process.env.REDIS_PASSWORD || '',

  /**
   * Default time-to-live (seconds) for cache entries.
   * Default: 3600
   */
  ttl: process.env.REDIS_TTL ? parseInt(process.env.REDIS_TTL, 10) : 3600,

  /**
   * Prefix added to all Redis keys generated by the app.
   * Default: '2Connect:'
   */
  keyPrefix: process.env.REDIS_PREFIX || '2Connect:',

  /**
   * Enables TLS when set to the string 'true'.
   * Default: false
   */
  tls: String(process.env.REDIS_TLS) === 'true',
}));
