/**
 * EMAIL_JOB_EXECUTION_TIME_IN_DAYS
 * --------------------------------
 * - Controls how often the email job runs.
 * - Allowed values: 1 to 7 (integer)
 *   1 => every day at 00:00:00 UTC
 *   2 => every 2nd day at 00:00:00 UTC (1,3,5,...)
 *   7 => roughly once a week at 00:00:00 UTC (1,8,15,...)
 */
export const EMAIL_JOB_EXECUTION_TIME_IN_DAYS = 1; // change 1–7 as needed

// Build cron string: sec min hour day-of-month month day-of-week
// Example result: "0 0 0 */3 * *"
export const EMAIL_JOB_CRON_EXPRESSION = `0 0 0 */${EMAIL_JOB_EXECUTION_TIME_IN_DAYS} * *`;

export const onboarding_questions = [
  // SECTION 1: identity
  {
    section: 'identity',
    code: 'gender',
    prompt: 'How do you identify? (Helps your AI agent address you correctly.)',
    narration: null,
    description: null,
    input_type: 'single_select',
    comma_separated: false,
    options: [
      {
        label: 'Male',
        value: 'Male',
      },
      {
        label: 'Female',
        value: 'Female',
      },
      {
        label: 'Other',
        value: 'Other',
      },
    ],
    suggestion_chips: 'Your pronouns? (he/him, she/her, they/them, etc.)',
    guide_text: '',
    is_required: true,
    display_order: 1,
    is_active: true,
    has_nested_question: false,
    nested_question: null,
  },
  {
    section: 'identity',
    code: 'age',
    prompt: 'What’s your age? (Helps match your career stage and peer group.)',
    narration: null,
    description: null,
    input_type: 'text',
    comma_separated: false,
    options: null,
    suggestion_chips: 'eg. 25',
    guide_text: '',
    is_required: true,
    display_order: 2,
    is_active: true,
    has_nested_question: false,
    nested_question: null,
  },
  {
    section: 'identity',
    code: 'resume_linkedin_bio',
    prompt: 'Share your background. Choose the option that works best for you.',
    narration: null,
    description: null,
    input_type: 'multi_select',
    comma_separated: false,
    options: [
      {
        label: 'Upload Resume',
        value: 'Upload Resume',
      },
      {
        label: 'LinkedIn profile',
        value: 'LinkedIn profile',
      },
      {
        label: 'Brief professional background',
        value: 'Brief professional background',
      },
    ],
    suggestion_chips: `Upload your resume and we'll do the magic`,
    guide_text: '',
    is_required: true,
    display_order: 3,
    is_active: true,
    has_nested_question: false,
    nested_question: null,
  },
  {
    section: 'identity',
    code: 'elevator_pitch',
    prompt: `Share your 20-second intro - your personal elevator pitch.`,
    narration: null,
    description:
      'What gets you fired up professionally, and what are you building/doing right now? Think of this like your highlight reel that will open door.',
    input_type: 'text',
    comma_separated: false,
    options: null,
    suggestion_chips: `Your professional one-liner Summarize yourself in 2–3 sentences`,
    guide_text: '',
    is_required: true,
    display_order: 4,
    is_active: true,
    has_nested_question: false,
    nested_question: null,
  },
  {
    section: 'identity',
    code: 'core_strength_1',
    prompt: 'What’s your #1 strength — the one people rely on you for?',
    narration:
      'Let’s capture your top three strengths so your AI agent knows exactly how to champion you.',
    description: null,
    input_type: 'text',
    comma_separated: false,
    options: null,
    suggestion_chips: `What's your standout skill?`,
    guide_text: '',
    is_required: true,
    display_order: 5,
    is_active: true,
    has_nested_question: false,
    nested_question: null,
  },
  {
    section: 'identity',
    code: 'core_strength_2',
    prompt: 'Great — what’s another strength you’re known for?',
    narration: null,
    description: null,
    input_type: 'text',
    comma_separated: false,
    options: null,
    suggestion_chips: 'Hit us with another strength!',
    guide_text: '',
    is_required: true,
    display_order: 6,
    is_active: true,
    has_nested_question: false,
    nested_question: null,
  },
  {
    section: 'identity',
    code: 'core_strength_3',
    prompt: 'And one more — what completes your top three?',
    narration: null,
    description: null,
    input_type: 'text',
    comma_separated: false,
    options: null,
    suggestion_chips: 'One more! What completes your power trio?',
    guide_text: '',
    is_required: true,
    display_order: 7,
    is_active: true,
    has_nested_question: false,
    nested_question: null,
  },
  // SECTION 2: core_objectives
  {
    section: 'core_objectives',
    code: 'primary_goal',
    prompt: 'If your AI agent could accomplish one thing for you, what would it be?',
    narration: null,
    description: null,
    input_type: 'single_select',
    comma_separated: false,
    options: [
      {
        label: 'Raising capital for my start-up',
        value: 'Raising capital for my start-up',
      },
      {
        label: 'Finding investment opportunities (as a VC, angel, etc.)',
        value: 'Finding investment opportunities (as a VC, angel, etc.)',
      },
      {
        label: 'Generating qualified sales leads for my business',
        value: 'Generating qualified sales leads for my business',
      },
      {
        label: 'Finding a mentor or career advisor',
        value: 'Finding a mentor or career advisor',
      },
      {
        label: 'Offering mentorship to others',
        value: 'Offering mentorship to others',
      },
      {
        label: 'Exploring strategic partnerships or collaborations',
        value: 'Exploring strategic partnerships or collaborations',
      },
      {
        label: 'Recruiting for a key role',
        value: 'Recruiting for a key role',
      },
      {
        label: 'General learning and professional development',
        value: 'General learning and professional development',
      },
    ],
    suggestion_chips: 'What should your AI prioritize above all else?',
    guide_text: '',
    is_required: true,
    display_order: 8,
    is_active: true,
    has_nested_question: true,
    nested_question: {
      kind: 'branches',
      branches: {
        'Raising capital for my start-up': [
          {
            code: 'funding_stage',
          },
          {
            code: 'target_check_size',
          },
          {
            code: 'key_metrics',
          },
        ],
        'Finding investment opportunities (as a VC, angel, etc.)': [
          {
            code: 'stage_preference',
          },
          {
            code: 'industry_focus_areas',
          },
        ],
        'Generating qualified sales leads for my business': [
          {
            code: 'ideal_customer_profile',
          },
          {
            code: 'buying_signals',
          },
        ],
        'Finding a mentor or career advisor': [
          {
            code: 'skills_to_learn',
          },
          {
            code: 'career_hurdles',
          },
        ],
        'Offering mentorship to others': [
          {
            code: 'mentorship_areas',
          },
          {
            code: 'ideal_mentees',
          },
        ],
        'Exploring strategic partnerships or collaborations': [
          {
            code: 'partnership_type',
          },
          {
            code: 'ideal_partner_profile',
          },
        ],
        'Recruiting for a key role': [
          {
            code: 'role_title_responsibilities',
          },
          {
            code: 'key_qualifications',
          },
          {
            code: 'culture_values',
          },
        ],
        'General learning and professional development': [
          {
            code: 'topics_exploring',
          },
          {
            code: 'learning_style',
          },
        ],
      },
    },
  },
  // SECTION 2: NESTED QUESTIONS
  {
    section: 'core_objectives',
    code: 'funding_stage',
    prompt: 'Where are you in your funding journey?',
    narration: `Your AI agent uses this to connect you with the right capital partners.`,
    description: null,
    input_type: 'text',
    comma_separated: false,
    options: null,
    suggestion_chips: `Let's match you with investors who actually get where you are! No point in talking to Series B folks if you're pre-revenue, right?`,
    guide_text: '',
    is_required: true,
    display_order: 8.11,
    is_active: true,
    has_nested_question: false,
    nested_question: null,
  },
  {
    section: 'core_objectives',
    code: 'target_check_size',
    prompt: 'What check size range makes sense for your raise?',
    narration: null,
    description: null,
    input_type: 'text',
    comma_separated: false,
    options: null,
    suggestion_chips: 'What check size range makes sense for you?',
    guide_text: '',
    is_required: true,
    display_order: 8.12,
    is_active: true,
    has_nested_question: false,
    nested_question: null,
  },
  {
    section: 'core_objectives',
    code: 'key_metrics',
    prompt: 'What key metrics or traction would you like to highlight?',
    narration: null,
    description: null,
    input_type: 'text',
    comma_separated: false,
    options: null,
    suggestion_chips: 'Share your best traction metrics (users, revenue, growth!)',
    guide_text: '',
    is_required: true,
    display_order: 8.13,
    is_active: true,
    has_nested_question: false,
    nested_question: null,
  },
  {
    section: 'core_objectives',
    code: 'stage_preference',
    prompt: 'Which stages do you prefer to invest in?',
    narration: `Let's zero in on deals that match your investor DNA! Whether you love the wild early days or prefer proven traction, tell us your zone.`,
    description: null,
    input_type: 'multi_select',
    comma_separated: false,
    options: [
      {
        label: 'Pre-seed',
        value: 'Pre-seed',
      },
      {
        label: 'Seed',
        value: 'Seed',
      },
      {
        label: 'Series A',
        value: 'Series A',
      },
      {
        label: 'Series B+',
        value: 'Series B+',
      },
      {
        label: 'Revenue-generating',
        value: 'Revenue-generating',
      },
      {
        label: 'Still pre-product',
        value: 'Still pre-product',
      },
    ],
    suggestion_chips: 'Where do you like to deploy capital?',
    guide_text: '',
    is_required: true,
    display_order: 8.21,
    is_active: true,
    has_nested_question: false,
    nested_question: null,
  },
  {
    section: 'core_objectives',
    code: 'industry_focus_areas',
    prompt: 'Which industries are most relevant to your work or interests?',
    narration: null,
    description: null,
    input_type: 'multi_select',
    comma_separated: false,
    options: [
      {
        label: 'AI',
        value: 'AI',
      },
      {
        label: 'Fintech',
        value: 'Fintech',
      },
      {
        label: 'Health Tech',
        value: 'Health Tech',
      },
      {
        label: 'Consumer',
        value: 'Consumer',
      },
      {
        label: 'Deep Tech',
        value: 'Deep Tech',
      },
      {
        label: 'Ed Tech',
        value: 'Ed Tech',
      },
      {
        label: 'Web3',
        value: 'Web3',
      },
      {
        label: 'Other',
        value: 'Other',
      },
    ],
    suggestion_chips: 'What sectors are you most excited about?',
    guide_text: '',
    is_required: true,
    display_order: 8.22,
    is_active: true,
    has_nested_question: false,
    nested_question: null,
  },
  {
    section: 'core_objectives',
    code: 'ideal_customer_profile',
    prompt: `Who's your dream customer? Paint the picture!`,
    narration:
      'The clearer your ICP, the better your AI agent can source real opportunities — not noise.',
    description: null,
    input_type: 'text',
    comma_separated: false,
    options: null,
    suggestion_chips: 'Describe your perfect-fit customer (role, company, size)',
    guide_text: '',
    is_required: true,
    display_order: 8.31,
    is_active: true,
    has_nested_question: false,
    nested_question: null,
  },
  {
    section: 'core_objectives',
    code: 'buying_signals',
    prompt: 'What signals tell  you a prospect is READY to buy?',
    narration: null,
    description: null,
    input_type: 'text',
    comma_separated: false,
    options: null,
    suggestion_chips: 'How do you spot someone with budget, authority, and urgency?',
    guide_text: '',
    is_required: true,
    display_order: 8.32,
    is_active: true,
    has_nested_question: false,
    nested_question: null,
  },
  {
    section: 'core_objectives',
    code: 'skills_to_learn',
    prompt: 'What skills would be meaningful for you to level up right now?',
    narration: `Let's match you with someone who's already mastered what you're trying to learn! The more specific, the better.`,
    description: null,
    input_type: 'text',
    comma_separated: false,
    options: null,
    suggestion_chips: 'Which skills would unlock your next chapter?',
    guide_text: '',
    is_required: true,
    display_order: 8.41,
    is_active: true,
    has_nested_question: false,
    nested_question: null,
  },
  {
    section: 'core_objectives',
    code: 'career_hurdles',
    prompt: 'What challenges or roadblocks are you working to overcome?',
    narration: null,
    description: null,
    input_type: 'text',
    comma_separated: false,
    options: null,
    suggestion_chips: `What's the hurdle you're trying to clear?`,
    guide_text: '',
    is_required: true,
    display_order: 8.42,
    is_active: true,
    has_nested_question: false,
    nested_question: null,
  },
  {
    section: 'core_objectives',
    code: 'mentorship_areas',
    prompt:
      'Where can you offer meaningful guidance? (The things you’ve mastered that others would benefit from.)',
    narration: `Your experience can shortcut someone else's struggle! Let's define where you can help most.`,
    description: null,
    input_type: 'text',
    comma_separated: false,
    options: null,
    suggestion_chips: 'What have you mastered that others are still figuring out?',
    guide_text: '',
    is_required: true,
    display_order: 8.51,
    is_active: true,
    has_nested_question: false,
    nested_question: null,
  },
  {
    section: 'core_objectives',
    code: 'ideal_mentees',
    prompt: 'Who would benefit most from your experience?',
    narration: null,
    description: null,
    input_type: 'text',
    comma_separated: false,
    options: null,
    suggestion_chips: 'Who do you feel most equipped to guide?',
    guide_text: '',
    is_required: true,
    display_order: 8.52,
    is_active: true,
    has_nested_question: false,
    nested_question: null,
  },
  {
    section: 'core_objectives',
    code: 'partnership_type',
    prompt:
      'What kind of collaboration would be a strong win for you? (Integration, Marketing, Sponsorship, Distribution, etc.)',
    narration: `Let's get crystal clear on partnerships that actually move the needle!`,
    description: null,
    input_type: 'text',
    comma_separated: false,
    options: null,
    suggestion_chips: 'Describe the collaboration that would be a big win!',
    guide_text: '',
    is_required: true,
    display_order: 8.61,
    is_active: true,
    has_nested_question: false,
    nested_question: null,
  },
  {
    section: 'core_objectives',
    code: 'ideal_partner_profile',
    prompt: 'Tell us about your ideal partner and how they’d make a difference for you.',
    narration: null,
    description: null,
    input_type: 'text',
    comma_separated: false,
    options: null,
    suggestion_chips: 'Describe your ideal partner (industry, size, location, vibe)',
    guide_text: '',
    is_required: true,
    display_order: 8.62,
    is_active: true,
    has_nested_question: false,
    nested_question: null,
  },
  {
    section: 'core_objectives',
    code: 'role_title_responsibilities',
    prompt: `What's the role and what will they own?`,
    narration: `The clearer the role, the better candidates you'll attract! Let's make it compelling.`,
    description: null,
    input_type: 'text',
    comma_separated: false,
    options: null,
    suggestion_chips: 'What will this person be crushing from day one?',
    guide_text: '',
    is_required: true,
    display_order: 8.71,
    is_active: true,
    has_nested_question: false,
    nested_question: null,
  },
  {
    section: 'core_objectives',
    code: 'key_qualifications',
    prompt: `What are the key qualifications or experience you're looking for?`,
    narration: null,
    description: null,
    input_type: 'text',
    comma_separated: false,
    options: null,
    suggestion_chips: `Must-haves vs nice-to-haves—what's critical?`,
    guide_text: '',
    is_required: true,
    display_order: 8.72,
    is_active: true,
    has_nested_question: false,
    nested_question: null,
  },
  {
    section: 'core_objectives',
    code: 'culture_values',
    prompt: 'What values and culture matter most for this role?',
    narration: null,
    description: null,
    input_type: 'text',
    comma_separated: false,
    options: null,
    suggestion_chips: 'What kind of work environment does this person need to thrive in?',
    guide_text: '',
    is_required: true,
    display_order: 8.73,
    is_active: true,
    has_nested_question: false,
    nested_question: null,
  },
  {
    section: 'core_objectives',
    code: 'topics_exploring',
    prompt: `What topics or areas are you most excited to explore?`,
    narration: `Tell us what you're curious about so we can connect you with the right people and ideas!`,
    description: null,
    input_type: 'text',
    comma_separated: false,
    options: null,
    suggestion_chips: 'What themes or skills are on your learning radar?',
    guide_text: '',
    is_required: true,
    display_order: 8.81,
    is_active: true,
    has_nested_question: false,
    nested_question: null,
  },
  {
    section: 'core_objectives',
    code: 'learning_style',
    prompt: 'How do you learn best? What format keeps you engaged and excited?',
    narration: null,
    description: null,
    input_type: 'text',
    comma_separated: false,
    options: null,
    suggestion_chips: 'Podcasts? Deep dives? Conversations? What works for you?',
    guide_text: '',
    is_required: true,
    display_order: 8.82,
    is_active: true,
    has_nested_question: false,
    nested_question: null,
  },
  // SECTION 3: ideal_connections
  {
    section: 'ideal_connections',
    code: 'preferred_roles_titles',
    prompt: 'What roles or titles would be most valuable for you to connect with?',
    narration: `Let's target the exact people who can move your goals forward! The more specific, the better.`,
    description: `List the job titles that make you think "I'd love to meet someone like this!"`,
    input_type: 'text',
    comma_separated: true,
    options: null,
    suggestion_chips: {
      values: ['Product Managers', 'Startup Founders', 'VCs', 'Wellness Coaches'],
    },
    guide_text: '',
    is_required: true,
    display_order: 9,
    is_active: true,
    has_nested_question: false,
    nested_question: null,
  },
  {
    section: 'ideal_connections',
    code: 'industries_of_interest',
    prompt: 'Which industries matter most to you now — or in the future?',
    narration: null,
    description: 'E.g., AI, Web3, FinTech, HealthTech, Climate, etc.',
    input_type: 'text',
    comma_separated: true,
    options: null,
    suggestion_chips: { values: ['AI', 'Web3', 'Fintech', 'HealthTech'] },
    guide_text: '',
    is_required: true,
    display_order: 10,
    is_active: true,
    has_nested_question: false,
    nested_question: null,
  },
  {
    section: 'ideal_connections',
    code: 'deal_breakers',
    prompt: 'What are your hard "NO" criteria?',
    narration: null,
    description: `This is your "hard pass" list—industries you avoid, stages you don't work with, etc.`,
    input_type: 'text',
    comma_separated: true,
    options: null,
    suggestion_chips: null,
    guide_text: '',
    is_required: true,
    display_order: 11,
    is_active: true,
    has_nested_question: false,
    nested_question: null,
  },
  // SECTION 4: style_prefs
  {
    section: 'style_prefs',
    code: 'introduction_pacing',
    prompt: 'How many introductions would you prefer? Daily discoveries or weekly gems?',
    narration: `Help us tailor the experience so every introduction feels natural and aligned with your style.`,
    description: null,
    input_type: 'single_select',
    comma_separated: false,
    options: [
      {
        label: 'Quality over Quantity: Only a few highly-vetted matches',
        value: 'Quality over Quantity: Only a few highly-vetted matches',
      },
      {
        label: `Steady Flow: A regular system of relevant connections while you're active on the platform`,
        value: `Steady Flow: A regular system of relevant connections while you're active on the platform`,
      },
      {
        label: 'Event-based: High volume during a specific time',
        value: 'Event-based: High volume during a specific time',
      },
    ],
    suggestion_chips: null,
    guide_text: '',
    is_required: true,
    display_order: 12,
    is_active: true,
    has_nested_question: false,
    nested_question: null,
  },
  {
    section: 'style_prefs',
    code: 'communication_style',
    prompt: 'What communication style feels most natural when meeting new people?',
    narration: `Your AI agent mirrors your tone so intros feel authentically you.`,
    description: null,
    input_type: 'single_select',
    comma_separated: false,
    options: [
      {
        label: 'Formal and direct',
        value: 'Formal and direct',
      },
      {
        label: 'Casual and conversational',
        value: 'Casual and conversational',
      },
      {
        label: 'Data-driven and to the point',
        value: 'Data-driven and to the point',
      },
    ],
    suggestion_chips: null,
    guide_text: '',
    is_required: true,
    display_order: 13,
    is_active: true,
    has_nested_question: false,
    nested_question: null,
  },
  // SECTION 5: extra
  {
    section: 'extra',
    code: 'anything_else',
    prompt: 'What other details or context would help your AI agent represent you perfectly?',
    narration: null,
    description: null,
    input_type: 'text',
    comma_separated: false,
    options: null,
    suggestion_chips: null,
    guide_text: '',
    is_required: true,
    display_order: 14,
    is_active: true,
    has_nested_question: false,
    nested_question: null,
  },
];
