export const RESPONSES = {
  signupSuccessResponse: {
    code: 201,
    message: 'success',
    result: {
      user: {
        id: '9bee8425-8acb-4c12-8631-9e609ef4c4fb',
        first_name: 'firstname',
        last_name: 'lastname',
        email: 'example9@example.com',
        is_email_verified: false,
        role: {
          id: '297169aa-6f0a-4668-9bed-ae3e545a1554',
          title: 'user',
        },
      },
      email_verification_code: '4303',
      expires_at: '2025-09-17T10:40:02.658Z',
    },
  },
  signupAccountALreadyExistsResponse: {
    code: 409,
    message: 'User with this email already exists',
    result: null,
  },
  verifyEmailCodeExpiredResponse: {
    code: 400,
    message: 'Invalid or expired code',
    result: null,
  },
  verifyEmailSuccessResponse: {
    code: 200,
    message: 'success',
    result: {
      user: {
        id: 'bdb334ca-6268-46ff-abbe-c50f85938efe',
        first_name: 'firstname',
        last_name: 'lastname',
        email: 'example5@example.com',
        is_email_verified: true,
        role: {
          id: '297169aa-6f0a-4668-9bed-ae3e545a1554',
          title: 'user',
        },
      },
      access_token:
        'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiZGIzMzRjYS02MjY4LTQ2ZmYtYWJiZS1jNTBmODU5MzhlZmUiLCJlbWFpbCI6ImV4YW1wbGU1QGV4YW1wbGUuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NTgxMDUyMTUsImV4cCI6MTc1ODQ1MDgxNX0.BgSH2hWj04EG8iywTVod-xNNnQvFN1a28ljI6SyWC2w',
    },
  },
  resendVerificationCodeEmailAlreadyVerified: {
    code: 400,
    message: 'Email is already verified',
    result: null,
  },
  resendVerificationCodeSuccess: {
    code: 200,
    message: 'success',
    result: {
      email_verification_code: '7655',
      expires_at: '2025-09-16T10:51:13.506Z',
    },
  },
  signinIncorrectCredentials: {
    code: 400,
    message: 'Incorrect email or password!',
    result: null,
  },
  signinEmailNotVerifierd: {
    code: 200,
    message: 'success',
    result: {
      user: {
        id: 'bdb334ca-6268-46ff-abbe-c50f85938efe',
        first_name: 'firstname',
        last_name: 'lastname',
        email: 'example5@example.com',
        is_email_verified: false,
        role: {
          id: '297169aa-6f0a-4668-9bed-ae3e545a1554',
          title: 'user',
        },
      },
      email_verification_code: '4324',
      expires_at: '2025-09-17T10:34:00.193Z',
      access_token: null,
    },
  },
  signinSuccess: {
    code: 200,
    message: 'success',
    result: {
      user: {
        id: '0fbfab45-3bd2-409d-981a-165e6a3f8aec',
        first_name: 'firstname',
        last_name: 'lastname',
        email: 'example15@example.com',
        is_email_verified: true,
        role: {
          id: '0c14adb3-164e-4677-a136-aa2940d3c090',
          title: 'user',
        },
      },
      access_token:
        'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwZmJmYWI0NS0zYmQyLTQwOWQtOTgxYS0xNjVlNmEzZjhhZWMiLCJlbWFpbCI6ImV4YW1wbGUxNUBleGFtcGxlLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzU4MDIwNTg5LCJleHAiOjE3NTgzNjYxODl9.nwPejkpUzz2VM7CRU8hYn4O1IQSpoVasBBLDhzXDQ7s',
    },
  },
  googleSigninSuccess: {
    code: 200,
    message: 'success',
    result: {
      user: {
        id: 'bd3403e9-ea67-4d70-8545-8d784a03cddb',
        email: 'example1@example.com',
        role: {
          id: '0222d051-ba18-4550-96bf-32c6423c4706',
          title: 'user',
        },
      },
      access_token:
        'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiZDM0MDNlOS1lYTY3LTRkNzAtODU0NS04ZDc4NGEwM2NkZGIiLCJlbWFpbCI6ImV4YW1wbGUxQGV4YW1wbGUuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NTgwMjM5NTgsImV4cCI6MTc1ODM2OTU1OH0.uq9taYPlLhZ-1C5IRRa6d-16tdmLt1undy1XRKTgnwM',
    },
  },
  forgotPassworduccess: {
    code: 200,
    message: 'success',
    result: {
      password_reset_code: '3758',
      expires_at: '2025-09-16T12:11:14.214Z',
    },
  },
  verifyResetPasswordCodeFailure: {
    code: 400,
    message: 'Invalid or expired code',
    result: null,
  },
  verifyResetPasswordCodeSuccess: {
    code: 200,
    message: 'success',
    result: {
      reset_password_token:
        'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZmYyNTMzNi1mYTMzLTRhNmYtOGQxMy1lM2QwZWNmMjIzNDciLCJraW5kIjoicmVzZXRfcGFzc3dvcmQiLCJpYXQiOjE3NTgxOTQyNzUsImV4cCI6MTc1ODE5NDU3NSwiYXVkIjoicGFzc3dvcmQtcmVzZXQiLCJpc3MiOiJyZWNpcHJvY2l0eS1hdXRoIn0.TznrLfnt1UtSapUs7lnYwHOZTNeiJPXrVv9GMhEWoQ8',
    },
  },
  resetPasswordSuccess: {
    code: 200,
    message: 'success',
    result: true,
  },
  updatePasswordIncorrectCreds: {
    code: 400,
    message: 'Incorrect password!',
    result: null,
  },
  updatePasswordSuccess: {
    code: 200,
    message: 'success',
    result: true,
  },
  logoutSuccess: {
    code: 200,
    message: 'success',
    result: true,
  },
  myProfileSuccess: {
    code: 200,
    message: 'success',
    result: {
      id: 'ea520469-be47-48dd-9718-5ae43d5a39bf',
      role_id: '9f942206-03df-42fb-96c8-c83ca00cc2dd',
      provider: 'password',
      first_name: 'firstname',
      last_name: 'lastname',
      email: 'example1@example.com',
      gender: null,
      age: null,
      date_of_birth: null,
      is_email_verified: true,
      email_notifications: true,
      timezone: null,
      onboarding_status: 'not_started',
      is_active: true,
      allow_matching: true,
      last_login_at: '2025-09-19T08:50:17.434Z',
      created_at: '2025-09-18T12:13:06.361Z',
      updated_at: '2025-09-19T08:50:17.435Z',
      deleted_at: null,
      role: {
        id: '9f942206-03df-42fb-96c8-c83ca00cc2dd',
        title: 'user',
      },
    },
  },
  getLatestSummarySuccess: {
    code: 200,
    message: 'success',
    result: {
      id: '16eb33c9-df7a-4c36-8eae-dc5f454363b3',
      summary: 'summary',
      status: 'draft',
    },
  },
  onboardingSections: {
    code: 200,
    message: 'success',
    result: [
      {
        id: 'f0f98768-a96d-4bc8-8feb-8a6faf35f4bf',
        title: 'Your Professional Identity & Foundation',
        code: 'identity',
        description:
          "Let's build your professional persona through a conversational experience. We'll help you define your goals, Identify ideal connections, and personalize your networking approach.",
        display_order: 1,
      },
      {
        id: '8d6cc859-bd30-4281-bfd9-551a8733e95a',
        title: 'Your Core Objectives',
        code: 'core_objectives',
        description:
          'Share your key professional objectives to help us connect you with valuable opportunities and collaborations.',
        display_order: 2,
      },
      {
        id: '482309ef-b47b-4880-a753-c7187c925b59',
        title: 'Defining Your Ideal Connections',
        code: 'ideal_connections',
        description:
          'Let us know your primary professional goal so our AI can start building your ideal network of connections.',
        display_order: 3,
      },
      {
        id: 'a53c92f1-b98a-4b10-9190-e9415c8a6cb3',
        title: 'Your Network Styles & Preferences',
        code: 'style_prefs',
        description: '',
        display_order: 4,
      },
      {
        id: '533b0ff7-4375-4980-b2c4-f0c3636df547',
        title: 'Extra',
        code: 'extra',
        description: '',
        display_order: 5,
      },
    ],
  },
  onboardingQuestions: {
    code: 200,
    message: 'success',
    result: {
      id: 'f0f98768-a96d-4bc8-8feb-8a6faf35f4bf',
      title: 'Your Professional Identity & Foundation',
      code: 'identity',
      description:
        "Let's build your professional persona through a conversational experience. We'll help you define your goals, Identify ideal connections, and personalize your networking approach.",
      display_order: 1,
      questions: [
        {
          id: '890ed4e0-e61f-4461-94e6-4bafdda7bb18',
          section_id: 'f0f98768-a96d-4bc8-8feb-8a6faf35f4bf',
          code: 'gender',
          prompt: 'What is your gender?',
          narration: null,
          description: null,
          input_type: 'single_select',
          options: [
            {
              label: 'Male',
              value: 'male',
            },
            {
              label: 'Female',
              value: 'female',
            },
            {
              label: 'Other',
              value: 'other',
            },
          ],
          suggestion_chips: null,
          is_required: false,
          display_order: 1,
          is_active: true,
          has_nested_question: false,
          nested_question: null,
          created_at: '2025-09-22T11:41:39.891Z',
          updated_at: '2025-09-22T11:41:39.891Z',
        },
        {
          id: '03a6cd71-d2d4-4c57-afe3-78003bca2d57',
          section_id: 'f0f98768-a96d-4bc8-8feb-8a6faf35f4bf',
          code: 'age',
          prompt: 'What is your age?',
          narration: null,
          description: null,
          input_type: 'text',
          options: null,
          suggestion_chips: null,
          is_required: false,
          display_order: 2,
          is_active: true,
          has_nested_question: false,
          nested_question: null,
          created_at: '2025-09-22T11:41:39.891Z',
          updated_at: '2025-09-22T11:41:39.891Z',
        },
        {
          id: 'f95ab7f9-e635-4779-82f4-f3e9b79fcb6c',
          section_id: 'f0f98768-a96d-4bc8-8feb-8a6faf35f4bf',
          code: 'resume_linkedin_bio',
          prompt: 'Please select any option or all available options.',
          narration: null,
          description: null,
          input_type: 'multi_select',
          options: [
            {
              label: 'Upload Resume',
              value: 'resume',
            },
            {
              label: 'LinkedIn profile link',
              value: 'linkedin',
            },
            {
              label: 'Brief professional background',
              value: 'bio',
            },
          ],
          suggestion_chips: null,
          is_required: false,
          display_order: 3,
          is_active: true,
          has_nested_question: false,
          nested_question: null,
          created_at: '2025-09-22T11:41:39.891Z',
          updated_at: '2025-09-22T11:41:39.891Z',
        },
        {
          id: 'd12ae513-2693-41b9-9e30-0fc12889e51a',
          section_id: 'f0f98768-a96d-4bc8-8feb-8a6faf35f4bf',
          code: 'elevator_pitch',
          prompt: 'Your "Elevator Pitch"?',
          narration: null,
          description:
            'What are you currently working on and what are you most passionate about in your professional life?',
          input_type: 'text',
          options: null,
          suggestion_chips: null,
          is_required: false,
          display_order: 4,
          is_active: true,
          has_nested_question: false,
          nested_question: null,
          created_at: '2025-09-22T11:41:39.891Z',
          updated_at: '2025-09-22T11:41:39.891Z',
        },
        {
          id: '55f1774d-1155-4b6e-9576-8f997975ce70',
          section_id: 'f0f98768-a96d-4bc8-8feb-8a6faf35f4bf',
          code: 'core_strength_1',
          prompt: '1. Write about your first core strength',
          narration:
            'What are the top 3 skills or areas of expertise you bring to the table in any professional relationship? Kindly provide each strength in a distinct response.',
          description: null,
          input_type: 'text',
          options: null,
          suggestion_chips: null,
          is_required: false,
          display_order: 5,
          is_active: true,
          has_nested_question: false,
          nested_question: null,
          created_at: '2025-09-22T11:41:39.891Z',
          updated_at: '2025-09-22T11:41:39.891Z',
        },
        {
          id: '0f9231a5-c560-439b-9346-33fd2a725df5',
          section_id: 'f0f98768-a96d-4bc8-8feb-8a6faf35f4bf',
          code: 'core_strength_2',
          prompt: '2. Write about your second core strength',
          narration: null,
          description: null,
          input_type: 'text',
          options: null,
          suggestion_chips: null,
          is_required: false,
          display_order: 5,
          is_active: true,
          has_nested_question: false,
          nested_question: null,
          created_at: '2025-09-22T11:41:39.891Z',
          updated_at: '2025-09-22T11:41:39.891Z',
        },
        {
          id: '7a1252cd-68b7-44b3-865e-20d542d3eb01',
          section_id: 'f0f98768-a96d-4bc8-8feb-8a6faf35f4bf',
          code: 'core_strength_3',
          prompt: '3. Write about your third core strength',
          narration: null,
          description: null,
          input_type: 'text',
          options: null,
          suggestion_chips: null,
          is_required: false,
          display_order: 5,
          is_active: true,
          has_nested_question: false,
          nested_question: null,
          created_at: '2025-09-22T11:41:39.891Z',
          updated_at: '2025-09-22T11:41:39.891Z',
        },
      ],
    },
  },
  resetOnoboardingDataSuccess: {
    code: 200,
    message: 'success',
    result: true,
  },
  submitOnboardingSectionSuccess: {
    code: 200,
    message: 'success',
    result: {
      onboarding_status: 'in_progress',
    },
  },
  submitOnboardingSectionAlreadySubmitted: {
    code: 400,
    message: 'section is already submitted',
    result: null,
  },
  updateOnboardingSectionSuccess: {
    code: 200,
    message: 'success',
    result: true,
  },
  onboardingProgress: {
    code: 200,
    message: 'success',
    result: {
      progress: 40,
    },
  },
  onboardingAnswers: {
    code: 200,
    message: 'success',
    result: [
      {
        section_id: '3f683e7c-38cd-479f-a2aa-a72a3a713e16',
        section_title: 'Your Professional Identity & Foundation',
        section_code: 'identity',
        section_description:
          "Let's build your professional persona through a conversational experience. We'll help you define your goals, Identify ideal connections, and personalize your networking approach.",
        display_order: 1,
        questions: [
          {
            question_id: 'bf880d3b-8797-4039-b64c-29edb910dfcd',
            prompt: 'What is your gender?',
            description: null,
            code: 'gender',
            type: null,
            is_required: true,
            display_order: 1,
            answer: 'female',
          },
          {
            question_id: 'd8999c5b-c151-41f3-8bdd-99bbd31d3546',
            prompt: 'What is your age?',
            description: null,
            code: 'age',
            type: null,
            is_required: true,
            display_order: 2,
            answer: 24,
          },
          {
            question_id: 'e589aafc-320b-49d2-95fb-665da815d1ff',
            prompt: 'Please select any option or all available options.',
            description: null,
            code: 'resume_linkedin_bio',
            type: null,
            is_required: true,
            display_order: 3,
            answer: {
              bio: 'Hi, I am a software engineer.',
              resume: 'www.s3Bucket.com',
              linkedIn: 'www.linkedIn.com',
            },
          },
          {
            question_id: '5cfbfdbc-fed1-4038-a97f-098dcdfcb760',
            prompt: 'Your "Elevator Pitch"?',
            description:
              'What are you currently working on and what are you most passionate about in your professional life?',
            code: 'elevator_pitch',
            type: null,
            is_required: true,
            display_order: 4,
            answer: 'this is my elevator pitch',
          },
          {
            question_id: '9015a0ab-3f7a-4e8d-b6cb-2f572cd10667',
            prompt: '1. Write about your first core strength',
            description: null,
            code: 'core_strength_1',
            type: null,
            is_required: true,
            display_order: 5,
            answer: 'this is my core strength # 1',
          },
          {
            question_id: '49c8234f-4b49-4dfc-ba0e-60e9eca075f1',
            prompt: '2. Write about your second core strength',
            description: null,
            code: 'core_strength_2',
            type: null,
            is_required: true,
            display_order: 5,
            answer: 'this is my core strength # 2',
          },
          {
            question_id: '70630570-93c3-4b3b-828a-e4cf7e85dc64',
            prompt: '3. Write about your third core strength',
            description: null,
            code: 'core_strength_3',
            type: null,
            is_required: true,
            display_order: 5,
            answer: 'this is my core strength # 3',
          },
        ],
      },
      {
        section_id: 'e574804a-8524-41a7-b18f-f9fc44da22b6',
        section_title: 'Your Core Objectives',
        section_code: 'core_objectives',
        section_description:
          'Share your key professional objectives to help us connect you with valuable opportunities and collaborations.',
        display_order: 2,
        questions: [
          {
            question_id: '52158a0c-56f9-47d3-8947-fc2f11dcca34',
            prompt:
              'What is the main objective you want your AI agent to focus on? (Select one primary goal)',
            description: null,
            code: 'primary_goal',
            type: null,
            is_required: true,
            display_order: 1,
            answer: 'raising_capital',
          },
          {
            question_id: '1c3cdd1e-b92b-481e-9530-0549c43b491e',
            prompt: 'What is your funding stage?',
            description: null,
            code: 'funding_stage',
            type: null,
            is_required: true,
            display_order: 1,
            answer: 200000,
          },
          {
            question_id: '8b16f42f-2da9-4a58-b7fa-2706126b73a2',
            prompt: 'Target check size?',
            description: null,
            code: 'target_check_size',
            type: null,
            is_required: true,
            display_order: 2,
            answer: 5000000,
          },
          {
            question_id: '18f19a72-4a95-4f0e-ac72-ddad4bb44700',
            prompt: 'Key metrics to share with aligned investors?',
            description: null,
            code: 'key_metrics',
            type: null,
            is_required: true,
            display_order: 3,
            answer: 'no key metrics',
          },
        ],
      },
      {
        section_id: 'c98456c9-c8d6-49f6-ab13-fdf1037265ea',
        section_title: 'Defining Your Ideal Connections',
        section_code: 'ideal_connections',
        section_description:
          'Let us know your primary professional goal so our AI can start building your ideal network of connections.',
        display_order: 3,
        questions: [
          {
            question_id: '7e0c1847-0ec6-4e78-830a-1439daa78702',
            prompt: 'Preferred roles/titles?',
            description:
              'What Job titles, roles are most relevent to you? Are there any instructions you wish to avoid?',
            code: 'preferred_roles_titles',
            type: null,
            is_required: true,
            display_order: 1,
            answer: 'Product Managers',
          },
          {
            question_id: 'da20d15b-53b4-4459-be4b-6d6e6a8159cc',
            prompt: 'Industries of interest:',
            description: 'E.g. AI, Web3',
            code: 'industries_of_interest',
            type: null,
            is_required: true,
            display_order: 2,
            answer: 'AI',
          },
          {
            question_id: '46e8546e-12b6-45a6-b9bb-c35c1cbb88c2',
            prompt: 'What is your funding stage?',
            description:
              'Are there any specific traits, backgrounds or experiences you value in potential connections?',
            code: 'connection_funding_stage',
            type: null,
            is_required: true,
            display_order: 3,
            answer: 'something',
          },
          {
            question_id: '292aee6d-49e5-47df-a4fe-0be0fdfe1437',
            prompt: 'Deal Breakers:',
            description:
              'What are the absolute "Deal Breakers" or qualifiers that would make a potential connection irrelevant to you? This helps your agent filter out noise before it ever reaches you.',
            code: 'deal_breakers',
            type: null,
            is_required: true,
            display_order: 3,
            answer: 'deal breaker',
          },
        ],
      },
      {
        section_id: '4cae3794-10a2-4424-aba6-f2a06960c6ba',
        section_title: 'Your Network Styles & Preferences',
        section_code: 'style_prefs',
        section_description: '',
        display_order: 4,
        questions: [
          {
            question_id: '2dcda6a8-7aaa-443a-8709-b4b7014db73b',
            prompt: 'Preferred volume of introductions',
            description: null,
            code: 'introduction_pacing',
            type: null,
            is_required: true,
            display_order: 1,
            answer: 'quality_over_quantity',
          },
          {
            question_id: 'd47b912c-8e5f-46df-b424-67596ba5221a',
            prompt: 'What communication style do you typically prefer when meeting new people?',
            description: null,
            code: 'communication_style',
            type: null,
            is_required: true,
            display_order: 2,
            answer: 'formal_direct',
          },
          {
            question_id: 'ceea4e20-ee07-4d18-bc94-132dab6561e6',
            prompt:
              'Once you and a potential match both consent, how should the introduction happen?',
            description: null,
            code: 'preferred_introduction_method',
            type: null,
            is_required: true,
            display_order: 3,
            answer: 'email_intro',
          },
        ],
      },
      {
        section_id: '61410836-3d14-4d35-946d-e45e2e891bcb',
        section_title: 'Extra',
        section_code: 'extra',
        section_description: '',
        display_order: 5,
        questions: [
          {
            question_id: '2ef8ef24-7813-41ba-aa4c-a531bb45ad4e',
            prompt: 'Share anything else?',
            description: null,
            code: 'anything_else',
            type: null,
            is_required: true,
            display_order: 1,
            answer: 'na',
          },
        ],
      },
    ],
  },
  saveFcmTokenSucccess: {
    code: 200,
    message: 'success',
    result: true,
  },
  requestAiSummarySucccess: {
    code: 200,
    message: 'success',
    result: true,
  },
  approveAiSummarySucccess: {
    code: 200,
    message: 'success',
    result: true,
  },
  updateProfileSuccess: {
    code: 200,
    message: 'success',
    result: true,
  },
  deleteProfileAvatarSuccess: {
    code: 200,
    message: 'success',
    result: true,
  },
  messageTemplateCreateSuccess: {
    code: 200,
    message: 'success',
    result: true,
  },
  messageTemplateCreateFailure: {
    code: 400,
    message: 'Maximum limit of message templates reached',
    result: null,
  },
  messageTemplateGetSingleSuccess: {
    code: 200,
    message: 'success',
    result: {
      id: '5ac32099-39b2-4ee8-85ea-471bc183416d',
      title: 'firstname',
      body: 'lastname',
      is_active: true,
    },
  },
  messageTemplateGetAllSuccess: {
    code: 200,
    message: 'success',
    result: [
      {
        id: '5ac32099-39b2-4ee8-85ea-471bc183416d',
        title: 'firstname',
        body: 'lastname',
        is_active: true,
      },
    ],
  },
  messageTemplateUpdateSuccess: {
    code: 200,
    message: 'success',
    result: {
      id: '16eb33c9-df7a-4c36-8eae-dc5f454363b3',
      user_id: '5bb7123e-f411-41e4-84c5-dd3214e7aba9',
      title: 'title_4',
      body: 'body_4',
      is_active: true,
      created_at: '2025-10-02T10:25:24.163Z',
      updated_at: '2025-10-02T10:26:09.318Z',
    },
  },
  messageTemplateUpdateFailure: {
    code: 400,
    message: 'At least one template must remain active.',
    result: null,
  },
  onboardingMatchesSuccess: {
    code: 200,
    message: 'success',
    result: null,
  },

  decideMatchSuccess: {
    code: 200,
    message: 'success',
    result: {
      id: '64c233e2-7a99-417f-a2a7-5bb2b9836410',
      status: 'pending',
      user_a_decision: 'approved',
      user_b_decision: 'pending',
    },
  },
  quickStatsSuccess: {
    code: 200,
    message: 'success',
    result: {
      total_matches: 18,
      successful_matches: 1,
      conversations: 1,
      perfect_matches: 1,
    },
  },
  aiMatchAnalyticsSuccess: {
    code: 200,
    message: 'success',
    result: {
      total_matches: 18,
      match_success_rate_after_ai_chat: 27.78,
      avg_persona_compatibility_score: 20,
      ai_chat_completion_rate: 50,
    },
  },
  submitMatchFeedbackSuccess: {
    code: 200,
    message: 'success',
    result: {
      id: '9ea5fcbb-a138-4b7a-bde5-62c158c684e1',
      user_a_id: '1275bf15-8e2d-4c81-8b16-87a2fe7812f6',
      user_b_id: '283c9e7f-3a8f-44b9-b088-7ed81648aa94',
      user_a_feedback: 'feedback',
      user_b_feedback: null,
    },
  },
  recentAgentActivitySuccess: {
    code: 200,
    message: 'success',
    result: {
      items: [
        {
          id: '0171176c-d5fb-4f3a-8f42-c0295eeedba7',
          event_type: 'Updated The Persona',
          event_time: '2025-10-17T11:39:14.618Z',
          metadata: null,
          created_at: '2025-10-17T11:39:14.618Z',
        },
        {
          id: 'edb84b87-5e33-459f-b38d-e6a371dd1ecb',
          event_type: 'Updated The Persona',
          event_time: '2025-10-15T07:47:33.624Z',
          metadata: null,
          created_at: '2025-10-15T07:47:33.624Z',
        },
      ],
      page: 1,
      limit: 10,
      total: 22,
      totalPages: 3,
      range: {
        from: '2025-07-16T12:21:04.761Z',
        to: '2025-10-24T12:21:04.761Z',
      },
    },
  },
  listMatchesSuccess: {
    code: 200,
    message: 'success',
    result: {
      meta: {
        page: 1,
        limit: 1,
        total: 3,
        pages: 3,
      },
      items: [
        {
          id: 'b774db7c-d61e-43d7-80b5-ee1aab4a50c9',
          match_date: '2025-11-12T12:43:29.822Z',
          status: 'pending',
          status_label: 'awaiting_other',
          feedback: 'Feedback has been collected',
          is_ai_chat_initiated: false,
          other_user: {
            id: 'cf269398-55ad-4887-8bdc-a5d0b74f70b0',
            name: 'Profile eight',
            designation: 'Member',
            objective: 'General learning and professional development',
          },
        },
      ],
    },
  },
  matchesCountSuccess: {
    code: 200,
    message: 'success',
    result: {
      pending: 64,
      approved: {
        approved: 2,
        awaiting_other: 1,
        total: 3,
      },
      passed: {
        passed_by_me: 9,
        passed_by_other: 6,
        passed: 1,
        total: 14,
      },
    },
  },
  agentReviewMatchesSuccess: {
    code: 200,
    message: 'success',
    result: {
      meta: {
        page: 1,
        limit: 1,
        total: 4,
        pages: 4,
      },
      items: [
        {
          id: '24085164-d56c-4f7e-9c23-bb9d375f7417',
          match_date: '2025-11-06T12:54:35.173Z',
          status: 'pending',
          status_label: 'pursued',
          ai_decision: 'approved',
          feedback: 'No Feedback was given',
          is_ai_chat_initiated: true,
          other_user: {
            id: '2cdd7c87-20da-4952-9b68-3a7bc73090f2',
            name: 'safina sa',
            designation: 'Member',
            objective: 'Finding a mentor or career advisor',
          },
        },
      ],
    },
  },
  agentReviewMatchesCountSuccess: {
    code: 200,
    message: 'success',
    result: {
      approved: 4,
      passed: 3,
    },
  },
  adminLoginSuccess: {
    code: 200,
    message: 'success',
    result: {
      user: {
        id: '9bee8425-8acb-4c12-8631-9e609ef4c4fb',
        email: 'admin@2connect.ai',
        first_name: 'Admin',
        last_name: 'User',
        role: {
          id: '297169aa-6f0a-4668-9bed-ae3e545a1554',
          title: 'admin',
        },
      },
      access_token:
        'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5YmVlODQyNS04YWNiLTRjMTItODYzMS05ZTYwOWVmNGM0ZmIiLCJlbWFpbCI6ImFkbWluQDJjb25uZWN0LmFpIiwicm9sZSI6InN1cGVyLWFkbWluIiwiaWF0IjoxNzU4MTA1MjE1LCJleHAiOjE3NTg0NTA4MTV9.TxL2hYn04EG8iywTVod-xNNnQvFN1a28ljI6SyWC2w',
    },
  },
  adminLoginInvalidCredentials: {
    code: 401,
    message: 'Invalid email or password',
    result: null,
  },
  adminAccessDenied: {
    code: 403,
    message: 'Access denied. Only admin can access this resource.',
    result: null,
  },
  adminLogoutSuccess: {
    code: 200,
    message: 'success',
    result: true,
  },
  listUsersSuccess: {
    code: 200,
    message: 'success',
    result: {
      data: [
        {
          id: '9bee8425-8acb-4c12-8631-9e609ef4c4fb',
          full_name: 'Liam Parker',
          email: 'liam.parker@email.com',
          gender: 'Male',
          age: 24,
          onboarding_status: 'Completed',
          account_status: 'Active',
          created_at: '2025-05-25T09:18:37.000Z',
          updated_at: '2025-05-25T09:18:37.000Z',
        },
      ],
      total: 1,
      page: 1,
      limit: 20,
      totalPages: 1,
    },
  },
  searchUsersSuccess: {
    code: 200,
    message: 'success',
    result: {
      data: [
        {
          id: '9bee8425-8acb-4c12-8631-9e609ef4c4fb',
          full_name: 'John Doe',
          email: 'john@email.com',
          gender: 'Male',
          age: 30,
          onboarding_status: 'Completed',
          account_status: 'Active',
          created_at: '2025-05-25T09:18:37.000Z',
          updated_at: '2025-05-25T09:18:37.000Z',
        },
      ],
      total: 1,
    },
  },
  userDetailSuccess: {
    code: 200,
    message: 'success',
    result: {
      user: {
        id: '7b6a5266-2bd8-477c-8641-82df2d3955b9',
        full_name: 'firstname lastname',
        email: 'example1@example.com',
        gender: null,
        age: null,
        date_of_birth: null,
        bio: null,
        objective: null,
        avatar: null,
        linkedin_profile: null,
        onboarding_status: 'Not started',
        is_active: true,
        account_status: 'Active',
        is_email_verified: true,
        email_notifications: true,
        allow_matching: true,
        timezone: null,
        last_login_at: '2025-10-22T12:07:54.367Z',
        created_at: '2025-10-14T13:23:15.568Z',
        updated_at: '2025-10-22T12:07:58.037Z',
      },
      documents: [],
      summary: {
        id: 'd131881a-a5f5-4643-bd08-a08cb6336120',
        user_id: '7b6a5266-2bd8-477c-8641-82df2d3955b9',
        summary_text: 'Professional summary text here...',
        status: 'draft',
        version: 3,
        created_at: '2025-10-21T09:41:27.245Z',
        updated_at: '2025-10-21T09:41:27.245Z',
      },
      match_analytics: [
        {
          label: 'User Match Success Rate',
          value: 71.4,
        },
        {
          label: 'User Match Reject Rate',
          value: 28.6,
        },
      ],
    },
  },
  listUserActivityLogsSuccess: {
    code: 200,
    message: 'success',
    result: {
      data: [
        {
          id: 'log-id-1',
          user_id: '9bee8425-8acb-4c12-8631-9e609ef4c4fb',
          user: {
            id: '9bee8425-8acb-4c12-8631-9e609ef4c4fb',
            full_name: 'Liam Parker',
            email: 'liam.parker@email.com',
          },
          event_type: 'login',
          event_time: '2025-10-22T10:30:00.000Z',
          metadata: {
            ip_address: '192.168.1.1',
            user_agent: 'Mozilla/5.0...',
          },
          created_at: '2025-10-22T10:30:00.000Z',
        },
      ],
      total: 1,
      page: 1,
      limit: 20,
      totalPages: 1,
    },
  },
  setUserActivationSuccess: {
    code: 200,
    message: 'success',
    result: {
      user: {
        id: '9bee8425-8acb-4c12-8631-9e609ef4c4fb',
        full_name: 'Liam Parker',
        email: 'liam.parker@email.com',
        gender: 'Male',
        age: 24,
        onboarding_status: 'Completed',
        account_status: 'Active',
        is_active: true,
        created_at: '2025-05-25T09:18:37.000Z',
        updated_at: '2025-05-25T09:18:37.000Z',
      },
    },
  },
  userManagementEnumsSuccess: {
    code: 200,
    message: 'success',
    result: {
      sort_fields: [
        { label: 'Created At', value: 'created_at' },
        { label: 'Updated At', value: 'updated_at' },
        { label: 'First Name', value: 'first_name' },
        { label: 'Last Name', value: 'last_name' },
        { label: 'Email', value: 'email' },
        { label: 'Age', value: 'age' },
      ],
      sort_orders: [
        { label: 'ASC', value: 'ASC' },
        { label: 'DESC', value: 'DESC' },
      ],
      account_statuses: [
        { label: 'Active', value: 'active' },
        { label: 'Inactive', value: 'inactive' },
      ],
      onboarding_statuses: [
        { label: 'Not Started', value: 'not_started' },
        { label: 'In Progress', value: 'in_progress' },
        { label: 'Completed', value: 'completed' },
      ],
      genders: [
        { label: 'Male', value: 'male' },
        { label: 'Female', value: 'female' },
        { label: 'Other', value: 'other' },
      ],
    },
  },
  userNotFound: {
    code: 404,
    message: 'User not found',
    result: null,
  },
  unauthorized: {
    code: 401,
    message: 'Unauthorized',
    result: null,
  },
  forbidden: {
    code: 403,
    message: 'Forbidden',
    result: null,
  },
  badRequest: {
    code: 400,
    message: 'Bad request',
    result: null,
  },
  dashboardCountsSuccess: {
    code: 200,
    message: 'Dashboard counts retrieved successfully',
    result: [
      { label: 'Total Users', value: 150 },
      { label: 'Active Users', value: 120 },
      { label: 'AI Generated Summaries', value: 85 },
    ],
  },
  userSignupStatisticsSuccess: {
    code: 200,
    message: 'User signup statistics retrieved successfully',
    result: [
      { label: 'Week 1', value: 5 },
      { label: 'Week 2', value: 12 },
      { label: 'Week 3', value: 8 },
      { label: 'Week 4', value: 15 },
      { label: 'Week 5', value: 10 },
      { label: 'Week 6', value: 18 },
    ],
  },
  userOnboardingStatisticsSuccess: {
    code: 200,
    message: 'success',
    result: [
      { status: 'not_started', label: 'Not Started', count: 12 },
      { status: 'in_progress', label: 'In Progress', count: 0 },
      { status: 'completed', label: 'Completed', count: 31 },
    ],
  },
  commonCoreObjectivesSuccess: {
    code: 200,
    message: 'success',
    result: [
      { label: 'Raising Capital', count: 12 },
      { label: 'Networking', count: 8 },
      { label: 'Career Growth', count: 5 },
    ],
  },
  matchAcceptanceRatesSuccess: {
    code: 200,
    message: 'success',
    result: [
      { status: 'approved', label: 'Approved', count: 120, percent: 40 },
      { status: 'declined', label: 'Declined', count: 60, percent: 20 },
      { status: 'pending', label: 'Pending', count: 120, percent: 40 },
    ],
  },
  aiConversationSuccessMetricsSuccess: {
    code: 200,
    message: 'AI conversation success metrics retrieved successfully',
    result: [
      {
        label: 'Successful AI-to-AI Alignments',
        data: [
          { label: 'Week 1', value: 120 },
          { label: 'Week 2', value: 450 },
          { label: 'Week 3', value: 380 },
          { label: 'Week 4', value: 490 },
          { label: 'Week 5', value: 420 },
          { label: 'Week 6', value: 400 },
        ],
      },
      {
        label: 'Conversations Marked as Rejected',
        data: [
          { label: 'Week 1', value: 80 },
          { label: 'Week 2', value: 200 },
          { label: 'Week 3', value: 150 },
          { label: 'Week 4', value: 100 },
          { label: 'Week 5', value: 120 },
          { label: 'Week 6', value: 85 },
        ],
      },
      {
        label: 'Human Intervention',
        data: [
          { label: 'Week 1', value: 50 },
          { label: 'Week 2', value: 170 },
          { label: 'Week 3', value: 120 },
          { label: 'Week 4', value: 100 },
          { label: 'Week 5', value: 150 },
          { label: 'Week 6', value: 200 },
        ],
      },
    ],
  },
} as const;
